name: nookly
description: A comprehensive dating application built with Flutter.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.4
  
  # Network & API
  dio: ^5.4.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1

  # Google Sign-In
  google_sign_in: ^6.1.6
  googleapis_auth: ^1.4.1

  path_provider: ^2.1.2
  
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_card_swiper: ^6.0.0
  just_audio: ^0.9.36
  
  # Utils
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  geolocator: ^10.1.0
  app_links: ^3.4.5
  
  # Encryption for E2EE
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # OTP Input Widget
  pin_code_fields: ^8.0.1
  
  # Timer for resend functionality
  timer_builder: ^2.0.0
  
  # Testing
  injectable: ^2.3.2
  dartz: ^0.10.1
  http: ^1.1.0
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  record: ^6.0.0
  socket_io_client: ^2.0.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  bloc_test: ^9.1.4
  injectable_generator: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#234481"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#234481"
    theme_color: "#667eea"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/ 