name: nookly
description: A comprehensive dating application built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Agora
  agora_rtc_engine: ^6.2.6
  permission_handler: ^11.0.1
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Network & API
  dio: ^5.4.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1


  path_provider: ^2.1.2
  
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_card_swiper: ^6.0.0
  just_audio: ^0.9.36
  
  # Utils
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  geolocator: ^10.1.0
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  injectable: ^2.3.2
  dartz: ^0.10.1
  http: ^1.1.0
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  record: ^6.0.0
  socket_io_client: ^2.0.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  bloc_test: ^9.1.4
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/ 